/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package basicgui;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;

/**
 *
 * @author paramstudent
 */
public class Demo extends java.awt.Frame {

    /**
     * Creates new form Demo
     */
    public Demo() {
        initComponents();
        this.addWindowListener(new WindowAdapter() {
            @Override
        public void windowClosing(WindowEvent e){
            System.exit(0);
        }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Demo().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables



   
}
